### ISSUE TITLE
Some discussions on your design decisions

### ISSUE THREAD

**Issue by NutanNiraula** [rv928/SurveyApp#2]
@rv928 Hi there again, I am going to provide you my review to start a discussion. Please take this as a two way process and feel free to share examples, additional context or even raise concerns on each of these. This is nowhere near an exhaustive list but things I noticed while I skimmed through your code. The goal is to understand your decision process.

1.  One thing I noticed was that you were using swifty JSON over swift's Encodable/Decodable, it's not to judge it as good or bad but I would love to know your opinion on it. It's completely open ended discussion so, please feel free to share your opinion.

2. Another thing I noticed was there were empty files in survey detail. I would like to know your opinion on creating template and following a set architecture and having empty files or breaking the pattern to just use MVC, for example how would you approach a thank you page that has no additional functionality at all? Again, this is a open question so, there is no right/wrong, I just want to know your opinions.

3. You have not used any linters, what is your opinion on swiftLint for example?

4. There are couple of interesting decisions I see in your implementation, I just want you to know that I appreciate those like for example you have tried to use test spys and seeds, UI tests and accessibility identifiers were nice touch. Adding keychain, and adding a interceptor layer for retrying and header adaption were nice. You removed the default comments and cleaned up files like in appDelegates and viewcontrollers that was nice. ✌️  

5. One thing I wanted to specifically tell you was to use enum instead of structs to organize namespaces for static constants. Can you tell me why I would say something like that? What would be the difference between struct and enum in this case?

6. Your tests were crashing when I tried to run. I want to know your opinion about the automation in projects, like CI/CD. What do you think are important in considering automation and defining good process?

**Comment by rv928** [comment]
Hi @NutanNiraula ,
Thanks for reviewed code comments and giving your time for discussion about design process decisions.

1. Though I usually use codable and decodable. we should try to avoid third-party libraries until we are not able to achieve those functionalities using in-built provided frameworks. But some third parties like Alarmofire, SwiftyJSON are stable and trustworthy, providing more flexibility to use in the application. Here I used SwiftyJSON. Because swiftyJSON will save the number of coding lines in the model object. If I use Codable I need to first declare properties with type, to map properties with keys using CodingKeys, then I need to decode values from Decoder. These steps will consume double lines of code in Codable. While in SwiftyJSON just declare properties and map directly values to it. SwiftyJSON handles null values nicely.

2. I created files manually for VIP clean swift architecture. So I forgot to add protocol and dependency stuff in those files because I think there will be no use of it. Here survey detail has no logic just push and pop view controller. But in real time applications, we mostly have something to do in each view controllers either it is connected to the left side or on the right side. For your specified case thank you page: I think we should stick to the same architecture in the whole application. We should not combine 2 architectures in the same project. Either we should VIP clean swift or should use MVC.

3. I set up rules before the application development starts :D haha. So I am assuming I followed all the rules that I listed or decided to develop the project. I didn’t use SwiftLint previously though I would like to learn about it in the future. It’s a very good tool to set up predefined rules when working in a big team to make clean code without warnings, errors, naming conventions and unused declaration.

4. Thanks I am trying to improve my skills day by day.

5. struct and enums both are values types. For your specified case, I think we should use enum to declare static constants. Because if we use a struct, there will be a chance, someone will alloc it and create an object. But for enums we can’t create instant for this case.For ex, struct UIConstant {
  static let appColor = "#FF6666"
}
 Let constant = UIConstant(). ======. No error , anyone will use it.
Enum UIConstant {
static let appColor = "#FF6666"
}
Let constant = UIConstant() ==.==== Error : UIConstant cannot be constructed because it has no accessible initializers
So the conclusion is, I should use enum for this type of case instead of structure. Sorry :) 

6. Sorry for 1 unit test case is causing a crash. CI/CD is the best practice for automation in iOS app development. For CI require to write unit test and UI test cases, writing unit and UI test cases provide more scalable and bug-free applications with 99% of chance of developer side bug-free app. (ex. some not guessable crash) Another case: If we are working on large scale applications (ex. Banking app). This app has many major modules like Lending, Deposit, Bond. There will be different teams for a different module. Each team has iOS, Android, and backend developers. So in some cases, one team Lending has developed the Lending feature and Deposit team is now doing maintenance for the lending feature. If one developer is going to commit some code (Reviewed by some dev). And code is causing a crash. Which can affect both teams. and running build on jenkins which are on testing by QA.
If we use the CI / CD pipeline with Jenkins here. If the developer is trying to commit code and generating a pull request. He needs to run Jenkins build for a related feature once he commits. If a build fails he needs to modify code and make it clean and then we can say 99% bug free code will merge to develop the branch.

**Comment by NutanNiraula** [comment]
Thanks for your answer, the other members from our team will be evaluating your codebase and your performance in previous stages and get back to you soon. It was a pleasure talking with you and going through your codebase. Good luck. 🍀
